### PR TITLE
Plugins Work and Load Properly #20

### PR DESCRIPTION
**Pull request by yungtechboy1**
Plugins and Commands can now be loaded to the server from the Plugins Folder

### CODE REVIEW

**Comment by generalwrex** [comment]
This seems to be referencing your testplugin still ;)

Solution project file "TestPlugin.csproj" cannot be found.

I love AppVeyor! lol

**Comment by generalwrex** [comment]
Something strange happened when i tried to merge the pull request, all the files you added to the project were missing from the project folder?

**Comment by generalwrex** [comment]
The  projects you're using to refrence to add in features, make sure you ignore them with the gitignore file before you commit ;)

**Comment by yungtechboy1** [comment]
Hahahah! I found the Issue! I didnt actually push the comments that add the commands support! XD Im such a noob!

**Pull request merged**
